import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'bg-purple-500/10',
    'text-purple-400',
    'hover:border-purple-500/30',
    'from-purple-500/10',

    'bg-teal-500/10',
    'text-teal-400',
    'hover:border-teal-500/30',
    'from-teal-500/10',

    'bg-cyan-500/10',
    'text-cyan-400',
    'hover:border-cyan-500/30',
    'from-cyan-500/10',

    'text-white/80',
    'bg-white/5',
    'hover:bg-white/10',
    'border-white/5',
    'border-white/10',

    'text-white',
    'text-blue-400',
    'text-gray-300',
    'text-xs',
    'text-sm',
    'text-2xl',
    'text-5xl',
    'font-bold',
    'font-medium',

    'grid-cols-2',
    'lg:grid-cols-3',
    'gap-8',
    'space-y-2',
    'space-y-3',
    'space-y-6',
    'px-6',
    'px-8',
    'py-24',
    'py-4',
    'py-8',
    'py-16',
    'max-w-7xl',
    'mb-16',
    'mb-6',
    'mb-4',
    'mb-8',
    'mt-6',
    'mt-1',
    'p-8',
    'px-3',
    'py-1',
    'py-3',
    'pt-6',
    'w-1.5',
    'h-1.5',
    'w-2',
    'h-2',
    'w-4',
    'h-4',

    'flex',
    'grid',
    'items-start',
    'items-center',
    'justify-between',
    'justify-center',
    'flex-shrink-0',
    'gap-2',
    'flex-1',
    'flex-grow',
    'flex-col',

    'max-h-[500px]',
    'max-h-0',
    'opacity-0',
    'opacity-100',
    'duration-300',
    'duration-500',
    'ease-in-out',
    'group-hover:opacity-100',
    'transition-all',
    'transition-opacity',
    'transition-colors',
    'transition-transform',
    'transform-gpu',
    'will-change-transform',

    'rounded-xl',
    'rounded-lg',
    'rounded-full',
    'overflow-hidden',
    'relative',
    'absolute',
    'inset-0',
    'flex-grow',
    'flex-1',
    'flex-shrink-0',
    'min-w-0',
    'whitespace-nowrap',
    'line-clamp-1',
    'text-center',
    'min-h-screen',
    'bg-slate-900',
    'inline-flex',
    'backdrop-blur-sm',
    'bg-opacity-70',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
      },
      animation: {
        starfieldForward: 'starfieldForward var(--duration) linear infinite',
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-in': 'slideIn 0.5s ease-out',
        pulse: 'pulse 8s ease-in-out infinite',
        float: 'float 6s ease-in-out infinite',
        shine: 'shine 8s linear infinite',
        'enhanced-pulse':
          'enhancedPulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        starfieldForward: {
          '0%': {
            transform: 'translate3d(0, 0, -100px) scale(0.05)',
            opacity: '0',
          },
          '20%': { opacity: 'var(--initial-opacity, 0.2)' },
          '70%': { opacity: 'var(--max-opacity, 0.8)' },
          '100%': {
            transform: 'translate3d(0, 0, 1000px) scale(1.5)',
            opacity: '0',
          },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
