name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'  # Added cache for faster builds
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: '/ai-innovation-lab-v2'  # Add base path as env variable
          
      - name: Add .nojekyll file
        run: |
          touch ./out/.nojekyll
          
      - name: Create 404.html
        run: |
          cat > ./out/404.html << 'EOL'
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Redirecting...</title>
              <script>
                const segment = '/ai-innovation-lab-v2';
                sessionStorage.redirect = segment + location.pathname + location.search;
                location.replace(segment);
              </script>
            </head>
            <body>
              <h1>Redirecting...</h1>
              <p>If you are not redirected automatically, click <a href="/ai-innovation-lab-v2">here</a>.</p>
            </body>
          </html>
          EOL

      - name: Update build info
        run: |
          echo "{\"buildDate\":\"$(date -u +'%Y-%m-%d %H:%M:%S')\",\"version\":\"${{ github.sha }}\"}" > ./out/build-info.json
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
